### ISSUE TITLE
TypeError: buffer.readUInt8 is not a function

### ISSUE THREAD

**Issue by jackiesun8** [NetEase/pomelo-cocos2d-js#13]
新版的使用方法赞一下。
现在报这个错，是怎么回事呢？

**Comment by fantasyni** [comment]
在什么情况下会出现这个错误？

**Comment by jackiesun8** [comment]
@fantasyni 我就直接添加进js文件，然后添加了示例代码，就提示这个错误了。cocos2d-js版本是3.5

**Comment by fantasyni** [comment]
浏览器还是native跑的？

**Comment by jackiesun8** [comment]
@fantasyni native的错误是：pomelo-cocos2d-js/dist/pomelo-cocos2d-js.js:3283:TypeError: buffer.readUInt8 is not a function，浏览器的错误是：:8001/pomelo-cocos2d-js/dist/pomelo-cocos2d-js.js:3283 Uncaught TypeError: undefined is not a function

**Comment by jackiesun8** [comment]
@fantasyni 经查，是服务器推送onChat消息时触发的，因为onChat有开启protobuf压缩，所以才报了上面的错误。目前buffer的类型是Uint8Array，所以没有readUInt8方法，nodejs里面的Buffer模块才有readUInt8方法

**Comment by jackiesun8** [comment]
这个问题该怎么解决呢？
