### ISSUE TITLE
可以考虑发布成一个pomelo-cocos2d-js-min.js文件吗？这样html5和jsb就可以共用同一个文件了

### ISSUE THREAD

**Issue by zj8487** [NetEase/pomelo-cocos2d-js#8]

**Comment by fantasyni** [comment]
ok，加入roadmap，这个文件，考虑使用 browserify 来替换 component，并提供grunt构建，可以构建min.js

**Comment by zj8487** [comment]
@fantasyni ,这个版本大概好久发布啊。非常希望将这个库使用bearcat进行依赖管理。

**Comment by fantasyni** [comment]
不好意思，这周我会处理下，尽快发布
